apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:latest
        ports:
        - containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: emqx
spec:
  type: NodePort
  ports:
  - port: 1883
    targetPort: 1883
    nodePort: 30083
  selector:
    app: emqx
